version: '3.9'
services:
    apache:
        build:
            context: bin/apache
        container_name: ${CONTAINER_NAME}apache
        ports:
            - ${PORT_APACHE}:80
            - ${PORT_APACHE_SSL}:443
        links:
            - php
        volumes:
            - ./config/apache/config/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./config/apache/sites-available/default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
            - ./www/${PROJECT}:/usr/local/apache2/htdocs/
    php:
        build:
            context: bin/php
        container_name: ${CONTAINER_NAME}php
        expose:
            - 9000
        volumes:
            - ./www/${PROJECT}:/usr/local/apache2/htdocs/
        #  - /config/php/php.ini:
    redis:
        build:
            context: bin/redis
        container_name: ${CONTAINER_NAME}redis
        depends_on:
            -  php
    mysql:
        build:
            context: bin/mysql
        container_name: ${CONTAINER_NAME}mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${PORT_MYSQL}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}