version: '3.9'
services:
    web:
        build:
            context: bin/web
        container_name: ${CONTAINER_NAME}docker_server_web
        ports:
            - ${PORT_APACHE}:80
            - ${PORT_APACHE_SSL}:443
        volumes:
            - ./config/web/sites-available/:/etc/apache2/sites-enabled/
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            - ./www/${PROJECT}:/var/www/html
    redis:
        build:
            context: bin/redis
        container_name: ${CONTAINER_NAME}docker_redis_apache
        depends_on:
            -  web
    mysql:
        build:
            context: bin/mysql
        container_name: ${CONTAINER_NAME}docker_mysql_apache
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${PORT_MYSQL}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}